name: Build and Test .NET Framework 4.8 Project

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.2.0

    - name: Restore NuGet Packages
      run: |
        curl -LO https://dist.nuget.org/win-x86-commandline/v6.8.0/nuget.exe
        ./nuget.exe restore SimpleDotNetObfuscator.sln

    - name: Build Solution (Release)
      run: msbuild SimpleDotNetObfuscator.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Build /verbosity:minimal

    - name: Run MSTest Tests
      run: |
        # Discover and run MSTest tests using vstest.console.exe
        $vsTestPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.TestTools.BuildTools -property installationPath
        $vstestConsole = Join-Path $vsTestPath "Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
        
        & "$vstestConsole" "SimpleDotNetObfuscator.Tests\bin\Release\SimpleDotNetObfuscator.Tests.dll" --logger:"trx"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/*.trx"
