name: .NET Framework Obfuscator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'

    - name: Restore NuGet packages
      run: nuget restore SimpleDotNetObfuscator.sln -PackagesDirectory packages

    - name: Build Release configuration
      run: |
        msbuild SimpleDotNetObfuscator.sln `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /p:OutputPath=bin\Release `
          /p:AllowUnsafeBlocks=true

    - name: Execute Unit Tests
      run: |
        $testDll = "SimpleDotNetObfuscator.Tests\bin\Release\SimpleDotNetObfuscator.Tests.dll"
        vstest.console.exe $testDll `
          /Logger:trx `
          /TestAdapterPath:"packages\MSTest.TestAdapter.2.2.10\build\_common" `
          /ResultsDirectory:TestResults

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults

    - name: Archive Obfuscator Binaries
      uses: actions/upload-artifact@v4
      with:
        name: obfuscator-release
        path: |
          SimpleDotNetObfuscator/bin/Release/*
          !SimpleDotNetObfuscator/bin/Release/*.pdb
